select
  --t.*,
  t.tablespace_name, t.contents,
  CASE t.contents
    WHEN 'PERMANENT' THEN
      'CREATE BIGFILE TABLESPACE ' || t.tablespace_name || ' DATAFILE ''/u02/oradata/ORCL/' || t.tablespace_name || '.DBF'' SIZE 32M REUSE AUTOEXTEND ON NEXT 1M;'
    WHEN 'TEMPORARY' THEN
      'CREATE BIGFILE TEMPORARY TABLESPACE ' || t.tablespace_name || ' TEMPFILE ''/u02/oradata/ORCL/' || t.tablespace_name || '.DBF'' SIZE 32M REUSE AUTOEXTEND ON NEXT 1M;'
  END AS CREATE_DDL
from dba_tablespaces t
where t.contents != 'UNDO' and t.tablespace_name not in ('SYSAUX','SYSTEM','TEMP','USERS')
order by t.tablespace_name;

/*
CREATE BIGFILE TABLESPACE PARK_DATA DATAFILE '/u02/oradata/orcl/PARK_IDX.dbf' SIZE 1G REUSE AUTOEXTEND ON NEXT 1M; --MAXSIZE 32767M LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO
CREATE BIGFILE TABLESPACE PARK_IDX DATAFILE '/u02/oradata/orcl/PARK_IDX.dbf' SIZE 1G REUSE AUTOEXTEND ON NEXT 1M; --MAXSIZE 32767M LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO
CREATE BIGFILE TEMPORARY TABLESPACE "PARK_TEMP" TEMPFILE '/u02/oradata/orcl/PARK_TEMP.dbf' SIZE 128M REUSE AUTOEXTEND ON NEXT 1M; --MAXSIZE 32767M EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1024K
*/
