select t.* from dba_profiles t where t.profile = 'DEFAULT'
--and t.resource_name in ('PASSWORD_LIFE_TIME','PASSWORD_GRACE_TIME')
order by t.resource_name;

/*
ALTER PROFILE "DEFAULT" LIMIT PASSWORD_GRACE_TIME UNLIMITED;
ALTER PROFILE "DEFAULT" LIMIT PASSWORD_LIFE_TIME UNLIMITED;
ALTER PROFILE "DEFAULT" LIMIT PASSWORD_LOCK_TIME UNLIMITED;
*/
