--CREATE OR REPLACE VIEW V_SIZE_SCHEMAS AS
SELECT owner, ROUND(SUM(bytes)/1024/1024,2) SIZE_MB, ROUND(SUM(bytes)/1024/1024/1024,2) SIZE_GB
FROM dba_segments
WHERE OWNER NOT IN ('SYS','SYSTEM','SYSMAN','DBSNMP','ORDSYS','ORDDATA','OLAPSYS','EXFSYS','LBACSYS','MDSYS','DMSYS','CTXSYS','TSMSYS','WMSYS','WKSYS','WK_TEST','XDB','OUTLN','APEX_030200','FLOWS_FILES','FLOWS_030000')
GROUP BY owner
ORDER BY owner;
