SELECT
  uid, user,
  SYS_CONTEXT('USERENV','SESSION_USER') SESSION_USER,
  SYS_CONTEXT('USERENV','CURRENT_SCHEMA') CURRENT_SCHEMA,
  SYS_CONTEXT('USERENV','PROXY_USER') proxy,
  SYS_CONTEXT('USERENV','PROXY_USERID') proxy_userid
FROM DUAL;
